Use `expect` syntax in ability_spec_helper
Requires RSpec::Matchers to be included in the user class,
otherwise specs fail with the following error:

Failure/Error: expect(policy.constantize.new(self, subject).send("#{action}?")).to be true

NoMethodError:
  undefined method `expect' for #<User:0x000055aa8508c3b8>
  Did you mean?  exec

Deprecation warning fixed:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /apps/nztrain/spec/support/ability_spec_helper.rb:6:in `block (3 levels) in <module:AbilitySpecHelper>'.